[annex-i]
:appendix-caption: Annex I

== Annex H: I3S Point Cloud Scene Layer Profile

The following are profiles of the common classes 3dSceneLayerInfo, attributeInfo, Store, Index, defaultGeometrySchema, 
vertexAttributes, and AttributeStatistics. Please note that most of these profiles of common and shared classes in the 
core I3S standard have additional mandatory elements

=== I3S point cloud Scene Layer (profile of 3dSceneLayerInfo
This section describes the point cloud scene layer. The following table describes 
the properties of the point cloud scene layer. The description provides guidance on the mandatory/allowed values for a 
property (or object) for a given property.

[width="90%",options="header"]
|===
|Property	|Type	|Description
|*id*	|integer	|A unique identifying number for the layer. For point cloud scene layer, only a single layer is supported, therefore, id is always 0.
|*layerType*	|string	|String indicating the layer type. +
_Shall_ be: `PointCloud`
|*name*	|string	|Represents the layer name.
|alias	|string	|Represents the alias layer name.
|desc	|string	|Description for the layer.
|copyrightText	|string	|Copyright information to be displayed with this layer.
|capabilities	|string[]	|Capabilities supported by this layer. +
Possible values for each array string: +
-	`View`: View is supported. +
-	`Query`: Query is supported.
|*spatialReference*	|<<spatialReference>> |An object containing the WKID or WKT identifying the spatial reference of the layer's geometry. No special point cloud guidance.
|heightModelInfo	|<<heightModelInfo>> |An object containing the vertical coordinate system information. No special point cloud guidance.
|serviceUpdateTimeStamp	|<<serviceUpdateTimeStamp>> |Object to provide time stamp when the I3S service or the source of the service was created or updated. No special point cloud guidance,
|store	|<<store>>	|The storage for the layer. Please reference the point cloud scene layer store profile below.
|attributeStorageInfo	|<<attributeInfo>> [] |List of attributes included for this layer. Please reference the point cloud scene layer attributeInfo profile below.
|drawingInfo	|<<drawingInfo>>  |	An object containing drawing information for the point cloud scene layer. 
|elevationInfo	|<<elevationInfo>> |An object containing elevation information. For point cloud scene layers, the following 
rules shall apply +
-	`mode` is mandatory and _SHALL_ be `absoluteHeight` +
-	`offset` is offset for the point cloud scene layer. The elevation unit is the coordinate systems units.
|fields	|<<Field>> [] | For the point cloud scene layer profile, the properties name and type are mandatory.
|===

Note: Properties in bold are mandatory

Below is an example JSON encoding of the point cloud scene layer definition. Please note that the “types” 
`pointCloudSplatAlgorithm` and `pointCloudStretchRenderer` are examples specific to what your clients support. 
Replace these types with whatever algorithms are appropriate on your development and 3d visualization environment. 
In the following example, `PointCloudStretchRenderer` defines the color of each point in a PointCloudLayer based on 
the value of a numeric attribute. `pointCloudSplatAlgorithm` is an algorithm for rendering points using sizes 
depending on point density. These are examples only.

```
{
    "id": 0,
    "layerType": "PointCloud",
    "name": "Test Data",
    "desc": "Nice Test data",
    "capabilities": [
      "View"
    ],
    "spatialReference": {
        "wkid": 4326,
        "latestWkid": 4326,
        "vcsWkid": 5703,
        "latestVcsWkid": 5703
    },
    "store": {
        "id": "",
        "profile": "PointCloud",
        "version": "2.0",
        "extent": [
            -122.45945212669568,
            38.298060753040346,
            -122.43014691292728,
            38.303939889306761
        ],
        "index": {
            "nodeVersion": 1,
            "boundingVolumeType": "obb",
            "nodesPerPage": 64,
            "lodSelectionMetricType": "density-threshold"
        },
        "defaultGeometrySchema": {
            "geometryType": "points",
            "header": [],
            "topology": "PerAttributeArray",
            "encoding": "lepcc-xyz",
            "vertexAttributes": {
                "position": {
                    "valueType": "Float64",
                    "valuesPerElement": 3
                }
            },
            "ordering": [
                "position"
            ]
        }
    },
    "attributeStorageInfo": [
        {
            "key": "1",
            "name": "ELEVATION",
            "encoding": "embedded-elevation"
        },
        {
            "key": "2",
            "name": "INTENSITY",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt16",
                "valuesPerElement": 1
            },
            "encoding": "lepcc-intensity"
        },
        {
            "key": "4",
            "name": "RGB",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 3
            },
            "encoding": "lepcc-rgb"
        },
        {
            "key": "8",
            "name": "CLASS_CODE",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 1
            }
        },
        {
            "key": "16",
            "name": "FLAGS",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 1
            }
        },
        {
            "key": "32",
            "name": "RETURNS",
            "ordering": [
                "attributeValues"
            ],
            "attributeValues": {
                "valueType": "UInt8",
                "valuesPerElement": 1
            }
        }
    ],
    "drawingInfo": {
        "renderer": {
            "pointSizeAlgorithm": {
                "type": "pointCloudSplatAlgorithm",
                "scaleFactor": 1,
                "minSize": 4
            },
            "pointsPerInch": 25,
            "field": "ELEVATION",
            "fieldTransformType": "none",
            "colorModulation": {
                "field": "",
                "minValue": 1,
                "maxValue": 255
            },
            "type": "pointCloudStretchRenderer",
            "stops": [
                {
                    "value": 23.91416560580215,
                  "color": [
                    88,
                    19,
                    252,
                    255
                  ]
                },
                {
                    "value": 59.9739474458430379,
                    "color": [
                        8,
                        252,
                        253,
                        255
                    ]
                },
                {
                    "value": 96.033729285883922,
                    "color": [
                        242,
                        254,
                        42,
                        255
                    ]
                },
                {
                    "value": 132.093511125924806,
                    "color": [
                        255,
                        43,
                        24,
                        255
                    ]
                }
            ]
        }
    },
    "elevationInfo": {
        "mode": "absoluteHeight"
    },
    "heightModelInfo": {
        "heightModel": "gravity_related_height",
        "vertCRS": "NAVD_1988",
        "heightUnit": "meter"
    }
} 
```

=== I3S point cloud scene layer: attributeInfo
List of attributes included for this point cloud scene layer.

[width="90%",options="header"]
|===
|Property	|Type	|Description
|*key*	|string	|Represents the attribute key. Key is the same as `id' used in the resource URL to fetch the binary buffers.
|*name*	|string	|The attribute name. Must be unique for this layer.
|ordering	|string[]	|Mapping between attribute to point. Only 1-to-1 is currently supported. +
Possible values for each array string: +
-	`attributeValues`
|encoding	|string	|Encoding (i.e. compression) for the attribute binary buffer if different from GZIP or no-compression. +
Possible values are: `+
-	``embedded-elevation: No binary buffer but stats for this pseudo attribute will be available. For example, point.z from the geometry should be used. +
-	`lepcc-intensity`: LEPCC compression for scaled integral type. +
-	lepcc-rgb`: LEPCC color compression for 3-channel RGB 8 bit.
|attributeValues	|<<value>> |Represents the description for value encoding, for example scalar or vector encoding.
|===

Note: Properties in *bold* are mandatory.

*Elevation pseudo-attribute*
 
 ```
 {
  "key": "1",
  "name": "ELEVATION",
  "encoding": "embedded-elevation"
} 
```

*Example: Color attribute*
 
 ```
 {
  "key": "4",
  "name": "RGB",
  "ordering": [
    "attributeValues"
  ],
  "attributeValues": {
    "valueType": "UInt8",
    "valuesPerElement": 3
  },
  "encoding": "lepcc-rgb"
} 
```

*Example: 8-bit uncompressed/GZIP compressed class-codes*

```
 {
  "key": "8",
  "name": "CLASS_CODE",
  "ordering": [
    "attributeValues"
  ],
  "attributeValues": {
    "valueType": "UInt8",
    "valuesPerElement": 1
  }
} 
```

=== I3S point cloud scene layer profile: Store

The following table provides information on the properties that describes storage for the PointCloud scene layer. Please note that there are Point Cloud specific profiles of the Index and defaultGeometryScheme classes.

[width="90%",options="header"]
|===
|Property	|Type	|Description
|id	|string	|Id for the store. Not currently used by the point cloud scene layer.
|*profile*	|string	|Defines the profile type of the scene layer as point cloud scene layer. +
Shall be: +
- PointCloud
|*version*	|string	|Point cloud scene layer store version.
|*extent*	|number[4]	|2D extent of the point cloud scene layer in the layers spatial reference units.
|*index*	|<<index>>	|Describes the index (i.e. bounding volume tree) of the layer.
|*defaultGeometrySchema*	|<<defaultGeometrySchema>> |Attribute description as field.
|geometryEncoding	|string	|MIME type for the encoding used for the Geometry Resources. For example: application/octet-stream; version=1.6.
|attributeEncoding	|string	|MIME type for the encoding used for the Attribute Resources. For example: application/octet-stream; version=1.6.
|===

Note: properties in *bold* are mandatory.

