[annex-e]

:appendix-caption: Annex E
== Scene Service Access to REST Resources. Informative

This is the description of a REST API for a Scene Service. Please note that the examples use the Esri ArcGIS REST implementation. Simply change the base URL pattern (see below) for access to the I3S services available on your system.
There is a set of REST resources also defined in the I3S format specification that are served out via different endpoints. 
There is a base URL that needs to be defined and used in all I3S scene service access REST resource instances. This base URL points to where your I3S host services and content are located. In addition there are 6 mandatory resource instances and 2 optional resource instances.

Mandatory:

- 3dSceneServiceInfo (JSON)
- 3dSceneLayerInfo (JSON)
- 3dNodeIndexDocument (JSON)
- SharedResources (JSON)
- TextureData (Binary)
- GeometryData (Binary)

Optional:

- FeatureData JSON (optional for Mesh-Pyramids profile)
- AttributeData (Binary)

This is the REST API for retrieval of these resources:

*Common Services Information*

- _URL Pattern_: http://<hostname>/<server-name>/rest/services/
- _Method_: GET
- _Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/
- _Returns_: List of all services running on the server instance.

*3dSceneServiceInfo*

- _URL Pattern_: <base-url>/<server-name>/SceneServer
- _Method_: GET
- _Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer
- _Returns_: Scene Service metadata and list of available layers.

*3dSceneLayerInfo*

- _URL_ Pattern: <scene-server-url>/layers/<layer-id>
- _Method_: GET
- _Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer/layers/0
- _Returns_: Detailed information about single layer, including symbology, field schema, and profile/store metadata, with a link to the root 3dNodeIndexDocument

*3dNodeIndexDocument*

- URL Pattern: <layer-url>/nodes/<node-id>
- Method: GET
- Example Service:http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer/layers/0/nodes/5-1-0-0-0
- Returns: A file describing a single node in the spatial index, with links to all associated resources such as FeatureData, textures, Geometry and SharedResources

*SharedResources*

- _URL Pattern_: <node-url>/shared/
- _Method_: GET
- |Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer/layers/0/nodes/5-1-0-0-0/features/0
- _Returns_: A feature data resource (bundle)

*FeatureData*

- _URL Pattern_: <node-url>/features/<feature-data-bundle-id>
- _Method_: GET
- _Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer/layers/0/nodes/5-1-0-0-0/features/0
- _Returns_: A feature data resource (bundle). In case of Points layer type, the feature data document contains positional information and could also include by value any attribute information associated with each feature. For layer types belonging to Mesh-Pyramids profile, this resource is optional as all required information to identify feature to geometry mapping is compactly stored with the binary geometry data. In addition, attribute data in Mesh-Pyramids profiles are stored as AttributeData resource as described in the I3S format specification.

*GeometryData*

- _URL Pattern_: <node-url>/geometries/<geometry-data-bundle-id>
- _Method_: GET
- _Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer/layers/0/nodes/5-1-0-0-0/geometries/0
- _Returns_: A geometry data resource (bundle)

*TextureData*

- _URL Pattern_: <node-url>/textures/<texture-data-bundle-id>
- _Method_: GET
- _Example Service_: http://scene.arcgis.com/arcgis/rest/services/Hosted/Buildings_San_Francisco/SceneServer/layers/0/nodes/1-3-0-0-0-0-0-0-0/textures/0_0
- _Returns_: A texture data resource (bundle). Refer to the I3S format specification for details on how different encodings and resolutions are encoded.

*AttributeData*

- _URL Pattern_: <node-url>/attributes/<attribute-data-bundle-id>
- _Method_: GET
- _Example Service_: http://3dcities.maps.arcgis.com/arcgis/rest/services/New_York_LoD2_3D_Buildings/SceneServer/layers/0/nodes/5-1-0-0-0/attributes/f_0/0
- _Returns_: An attribute data resource (bundle). Refer to the I3S format specification for details on how different types of attributes are encoded.
