== Additional Informative Information

=== 10.1	Flexibility
I3S is flexible and allows for different implementation choices for different types of 3D data or even for the same type of 3D data. The profile for a layer indicates the set of choices made. Choices supported by I3S and made use of by different profiles are described below. In each case the profile listed is the canonical profile for the corresponding layer-type. Here are a few implementation options:

.	The Minimum Bounding Volume (MBV) property can be represented as:
.. Minimum Bounding Sphere (MBS)
.. Oriented Bounding Box (OBB) 
.	Node structure
.. Expanded: Supports clients that want to get more complete meta-information about node’s position within the BVH hierarchy and its immediate neighborhood 
...	Each index node provides pointers to its parent, all its children, and sibling neighbors (including their MBVs). Used by: mesh-pyramids and points profiles
. Fixed-size: Supports paged access pattern 
Minimal structure elements: bounding volume; first-child reference; child-count; LoD selection data; etc.
.	Embedded versus Binary geometry content format
.. Embedded geometry: as text (JSON) in-lined with other metadata within featureData resource. This supports profiles where run-length encoding of feature-IDs along the vertex data is suboptimal Used by: the canonical points profile. 
.. Binary format: for voluminous, ready to render/use geometries and cached attributes. Both typed array buffer views as well as fixed format binary buffers are supported. 
...	The mesh-pyramids profile uses ‘array buffer views’ (ArrayBufferView follows the Khronos Typed Array specification)
.	LoD Selection based on different metricTypes: 
-	maxScreenThreshold – LoD switching based on screen ‘size’ of the node’s MBV. Used by: mesh-pyramids profile
-	screenSpaceRelative – LoD switching based on screen ‘scale’ of the node’s MBV. Used by: points profile
-	distancRangeFromDefaultCamera – LoD switching based on normalized distance of the node’s MBV from the camera. Used by: points profile

=== 10.2	Summary of I3S Defining Characteristics
In summary, here are other characteristics, including content data formats, which the scene layer may include: 

- Attributes may be included on individual entities, points, or on partial segments of meshes
- Attribute-based stylization may be modified by client software
- Multiple, alternative textures may be provided to optimize for per-platform performance and display
- Texture and attribute data be created as JSON for index and metadata, and binary for large geometries
- A Scene Layer Package format for distribution, or direct use, of the scene layer as a single file (see SLPK section)
- Direct access is enabled through optional paired services that expose query-able and updatable RESTful endpoints
- Explicit control over bounding index shape and per-node switching behavior to provide for optimized display and query;
- Bounding volume hierarchy (BVH) based on bounding spheres (MBS) as well as oriented bounding boxes (OBB);
- Scene layers may be created in Cartesian 3D or in global 3D world coordinate reference systems 
