== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

ISO / TC 211: ISO 19115-1:2014 Geographic information -- Metadata -- Part 1: Fundamentals (2014)

OGC: OGC 07-057r7, OGC Web Map Tile Service Implementation Standard (2010)

OGC: OGC 06-121r9, OGC Web Services Common (OWS Common) Encoding Standard (2010)

[NOTE]
====
Insert References here. If there are no references, state “There are no normative references”.

Smith, T.F., Waterman, M.S.: Identification of Common Molecular Subsequences.
J. Mol. Biol. 147, 195–197 (1981)


Foster, I., Kesselman, C.: The Grid: Blueprint for a New Computing Infrastructure.
Morgan Kaufmann, San Francisco (1999)

Foster, I., Kesselman, C., Nick, J., Tuecke, S.: The Physiology of the Grid: an Open
Grid Services Architecture for Distributed Systems Integration. Technical report,
Global Grid Forum (2002)

National Center for Biotechnology Information, http://www.ncbi.nlm.nih.gov

====
