== Conceptual Model for 2 Dimensional Euclidean Space Tiles and Tiling: Normative
This section defines the mandatory and recommended requirements of the core model for 2-D tiling of in Euclidean space. These elements are mandatory regardless and independent of the implementation platform, programming languages, encodings, or any other implementation specific and requirements. 

=== 2-D Core Conceptual Model Requirements

==== Requirement 1 - tessellation

include::requirements/REQ1_core-tessellation.adoc[]

Element name: TileTessellation

==== Requirement 2 - Tile Set Coordinate Reference System (CRS)

include::requirements/REQ2_core-tileset-crs.adoc[]

A tile scheme shall specify a coordinate reference system (CRS) that is consistent for a given tile set. The CRS for a given tile set could be based on an engineering datum or an earth centric datum. The CRS could be restricted to meet very specific requirements, say for visualization of pre-rendered tiles as defined in the WMTS standard. Further, at the core conceptual level, there is no requirement that all CRSs be the same for all tile sets in a tiled data store. 

Having the same CRS for all tile sets in a data store is a requirement that would be specified in a profile. For example, CDB specifies WGS 84 (EPSG4326) for all tiles.

Element name: TileSetCRS

==== Requirement 3 - Tile Set Units of Measure (UoM)

include::requirements/REQ3_core-tileset-uom.adoc[]

A tile scheme shall specify a unit of measure (UoM) for a tile set, such as meters or feet, that is consistent for any given tile set. The UoM may be specified in the CRS definition or may be different from the CRS definition. At the core conceptual level, there is no requirement that all UoMs be the same for all tile sets in a tiled data store. Having a consistent UoM across all tile sets is a requirement that would be specified in a profile. (Example conceptual mode element “TileUoM=ft”)

Element name: TileSetUOM

==== Requirement 4 - Tile Set Extent

include::requirements/REQ4_core-tileset-extent.adoc[]

