== Introduction

For many geospatial technology applications and use cases, there is the need (requirement!) to partition the space of interest. Examples are numerous. Within the OGC standards baseline, CDB defines how to partition the globe into a set of 2d tiles for many levels of detail. The Web Matrix Tile Set (WMTS) standard defines the rules and requirements for a tile matrix set as a way to index space based on a set of regular grids defining a domain (tile matrix) (tile matrix) for a limited list of scales in restricted set of Coordinate Reference Systems (CRS). The new - and more general - Tile Matrix Set standard specifies the concept of a tile matrix set and tile matrix set limits and its implementation in 2D space. Finally, I3S defines how to partition 3d space using a hierarchical, node-based spatial index structure in which each node’s payload may contain features with associated geometry, textures and attributes.

In geometry, space partitioning is the process of dividing a space (usually a Euclidean space) into two or more disjoint subsets. In other words, space partitioning divides a space into non-overlapping regions. Any point in the space can then be identified to lie in exactly one of the regions. 

Within that context, we can consider the requirements for partitioning space based on dimension. This OGC Abstract Specification presents a conceptual model for partitioning 2-D Euclidean space. Tiling of 2d Euclidian space is the most commonly known approach to partitioning space. However, there are common mandatory elements for any approach to partitioning space. This document defines the several common required elements that apply to any dimension and then follows with more specific requirements for the 2-D tiles and tiling.

Please note that in the preparation of this draft conceptual model, the tiling sections/extensions to CDB, GeoPackage, WMTS, and MVT were reviewed. The OGC DGGS standard and various Engineering Reports from the OGC Test Bed 13, Test Bed 14 and the Vector Tiles Pilot were also considered. Finally, the Tile Matrix Set candidate standard was reviewed. Much of this document is derived by abstracting what is contained in those existing and candidate standards and specifications.

The goal is to define a simple conceptual model that can support any and all requirements for tiled data stores and applications including extensions for visualization, portrayal, analytics, filtering, lelvels of detail, and so forth. These various use cases and/or workflows are not part of the core conceptual model but instead may be thought of as profiles or extensions of the model that restrict core requirements or define additional requirements. For example, the majority of the CDB standard that deals with tiles defines additional requirements such as level of detail to optimize the data store for that domain of interest.

=== Key concept - The assumption of a 2-D planar space

The tiling conceptual model defined in this document assumes that the target is tiling a two dimensional plane in Euclidean space. However, the content to be stored in a tiled structure is typically earth (or planetary body) referenced. Therefore, the transformation from a spheroidal coordinate system into a planar system is required. The following paragraph, extracted from the Tile Matrix Set Standard, describes the solution for coordinate reference systems other than geographic (Latitude, Longitude).

_As stated in OGC 08-015r6 Abstract Specification Topic 2: Spatial referencing by coordinates, a coordinate system is a set of mathematical rules for specifying how coordinates are to be assigned to points in space. A Coordinate Reference System (CRS) is a coordinate system that is related to the real world by a reference datum. An example of mathematical rules is the application of a sphere or an ellipsoid centered in the datum and the use of a projection to transform the sphere or the ellipsoid into a planar representation of the world._

The remainder of this abstract specification assumes that the space to be tiled is a two dimensional planar surace in Euclidean space.

=== Characteristics of a Conceptual Model

The terms and definitions clause in this Abstract Specification provides a short definition for "conceptual Model". However, for additional clarification, the following are characteristics of a good conceptual model. A conceptual model:

* is a representation of a system, made of the composition of concepts which are used to help people know, understand, or simulate a subject the model represents. A documented conceptual model represents 'concepts' (entities), the relationships between them, and a vocabulary.

* is explicitly defined to be independent of design or implementation concerns. The aim of a conceptual model is to express the meaning of terms and concepts used by domain experts to discuss the problem, and to find the correct relationships between different concepts.

* organizes the vocabulary needed to communicate consistently and thoroughly about the know-how of a problem domain.

* starts with a glossary of terms and definitions.  There is a very high premium on high-quality, design-independent definitions, free of data or implementation biases.  The model also emphasizes rich vocabulary.

* is always about identifying the correct choice of terms to use in communications, including statements of rules and requirements, especially where high precision and subtle distinctions need to be made.  The core concepts of a geospatial problem domain are typically quite stable over time.

==== Conceptual Model vs. Data Model

A conceptual model differs from a data model in important ways.  The goal of a conceptual model is to support the expression of natural-language statements, and supply their semantics — not unify, codify (and sometimes simplify) data.  Therefore the vocabulary included in a conceptual model is far richer, as suits knowledge-intensive problem domains.  In short, conceptual models are concept-centric; data models are thing-entity-or-class-centric.

Data models can usually be rather easily derived from conceptual models; the reverse is much harder (or impossible).  Like data models, conceptual models are often rendered graphically, but free of such distractions to stakeholders as cardinalities.
