== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== *Conceptual model* 
a description of common concepts and their relationships, particularly in order to facilitate exchange of information between parties within a specific domain [CEN ENV 1613:1994]. A conceptual model is explicitly chosen to be independent of design or implementation concerns.

=== *coordinate reference system*
coordinate system that is related to the real world by a datum [ISO 19111]

=== *coordinate system*
set of mathematical rules for specifying how coordinates are to be assigned to points [ISO 19111]

=== *equilateral triangle*
a triangle in which all three sides are equal. In the familiar Euclidean geometry, an equilateral triangle is also equiangular; that is, all three internal angles are also congruent to each other and are each 60°.

=== *extension*
a set of one or more conformance clauses that defines new options for an existing standard. Extensions are generally designed to add additional capabilities that are not part of the core standard. An example is OGC GeoPackage Extension for Tiled Gridded Coverage Data. [OGC TC PnP]

=== *hexagon*
a six-sided polygon or 6-gon. The total of the internal angles of any simple (non-self-intersecting) hexagon is 720°. A regular hexagon is defined as a hexagon that is both equilateral and equiangular. It is bicentric, meaning that it is both cyclic (has a circumscribed circle) and tangential (has an inscribed circle). All internal angles are 120 degrees.

=== *profile*
a pure subset of an existing standard including restrictions on or deletions of conformance clauses related to the subsetting. An example of a profile is the GML Simple Feature Profile. [ISO 19106:2004, Type 1 Profile]

=== *profile with extension(s)*
a set of one or more conformance clauses from a base standard that includes at least one new conformance clause (extension). [OGC TC PnP] An example is OpenGIS® Web Map Services - Profile for EO Products.

=== *space partitioning*
In geometry, space partitioning is the process of dividing a space (usually a Euclidean space) into two or more disjoint subsets (see also partition of a set). In other words, space partitioning divides a space into non-overlapping regions. Any point in the space can then be identified to lie in exactly one of the regions.

=== *tessellation*
partitioning of a space into a set of conterminous subspaces having the same dimension as the space being partitioned [ISO 19123]

NOTE: _the tiling of two dimensional space using one or more geometric shapes, called tiles, with no overlaps and no gaps. In mathematics, tessellations can be generalized to higher dimensions and a variety of geometries. Regular tessellations are made up entirely of congruent regular polygons all meeting vertex to vertex. There are only three regular tessellations. These consist of a network of equilateral triangles, squares or hexagons footnoteref:[note1,Irregular tessellations  consist of figures that aren't composed of regular polygons but still interlock without gaps or overlaps. Voronoi diagrams are an example of an irregular tessellation.]._

=== *tile*
a geometric shape with known properties that is the result of the tiling (tessellation) of a plane. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

=== *tiling*
The process of decomposing some space into lots of little pieces (tiles) that fit together without gaps or overlaps.

=== *tiling scheme*
a scheme that defines how space is partitioned into individual tiled units. The scheme defines the spatial reference system, the geometric properties of a tile, which space a uniquely identified tile occupies, and reversely which unique identifier corresponds to a space satisfying the geometric properties to be a tile.

NOTE: _While in the general sense, a tiling scheme is not restricted to a coordinate reference system or a tile matrix set and allows for other spatial reference systems such as DGGS and other organizations including irregular ones, the logical model in this abstract specification focuses on the 2-D case._


=== *tile set*
A set of tiles with common properties that meets the definition of a tessellation. In short, a collection of subsets of the plane, i.e. tiles, which cover the space without gaps or overlaps.
