== Conceptual Model for 2 Dimensional Euclidean Space Tiles and Tiling: Normative
This section defines the mandatory elements of the core model for 2-D tiling of in Euclidean space. These elements are mandatory regardless and independent of the implementation platform, programming languages, encodings, or any other implementation specific and requirements. 

=== 2-D Core Conceptual Model Requirements
Paragraph – intro text for the requirement class.

include::requirements/REQ_core-tessellation.adoc[]

==== Requirement 1
Paragraph - intro text for the requirement.

Use the following table for Requirements, number sequentially.

include::requirements/requirement.adoc[]

Dictionary tables for requirements can be added as necessary. Modify the following example as needed.

[width="90%",options="header"]
|===
|Names |Definition |Data types and values |Multiplicity and use
|name 1 |definition of name 1 |float |One or more (mandatory)
|name 2 |definition of name 2 |character string type, not empty |Zero or one (optional)
|name 3 |definition of name 3 |GML:: Point PropertyType |One (mandatory)
|===
