[[LogicalModel]]

== Logical Model for 2-D Euclidean Space Tiles and Tiling: Normative
This section defines the mandatory and recommended requirements of the core model for 2-D tiling of in Euclidean space. These elements are mandatory regardless and independent of the implementation platform, programming languages, encodings, or any other implementation specific and requirements. 

=== Restrictions to definitions of key concepts for the tiling of 2-D plane

The general definitions for the key concepts are restricted as follows for the 2-D case. The key restrictions are highlighted.

`*tile*`: A geometric shape with known properties that is the result of the tiling (tessellation) *of a 2-D plane*.

`*tile set`*: A set of tiles with common properties that meets the definition of the tile schema and tiled based on the tessellation rules. *Tiles in a tile set are non-overlapping.*

`*tessellation*`: The tiles and associated tile set are generated by a *regular* tesselation *of a 2-D plane*.

=== Base Requirement

==== Requirement 1 - Core

include::requirements/REQ1_core.adoc[]

=== Requirement Class Tile Set Schema

The following is the requirements class of the Tile Set Schema

include::requirements/rc-tileset-schema.adoc[]

This requirement class defines the requirements for defining a tile set.

==== Requirement 2 - Tile Set Identifier (ID)

include::requirements/REQ2_core-tileset-id.adoc[]

Each tile set in a tiled data store shall have a unique identifier. This identifier could be a number or an alphanumeric string. For example, the ID could be CodeType, as an adaptation of MD_Identifier class ISO 19115. An example of analphanumeric identifier might be "Parcels" or "Street Network".

Element name: TileSetIdentifier

==== Requirement 3 - Tile Set Coordinate Reference System (CRS)

include::requirements/REQ3_core-tileset-crs.adoc[]

A tile scheme shall specify a coordinate reference system (CRS) that is consistent for a given tile set. The CRS for a given tile set could be based on an engineering datum or an earth centric datum. The CRS could be restricted to meet very specific requirements, say for visualization of pre-rendered tiles as defined in the WMTS standard. Further, at the core conceptual level, there is no requirement that all CRSs be the same for all tile sets in a tiled data store. 

Having the same CRS for all tile sets in a data store is a requirement that would be specified in a profile. For example, CDB specifies WGS 84 (EPSG4326) for all tiles.

Element name: TileSetCRS

==== Requirement 4 - Tile Set Units of Measure (UoM)

include::requirements/REQ4_core-tileset-uom.adoc[]

A tile scheme shall specify a unit of measure (UoM) for a tile set, such as meters or feet, that is consistent for any given tile set. The UoM may be specified in the CRS definition or may be different from the CRS definition. At the core conceptual level, there is no requirement that all UoMs be the same for all tile sets in a tiled data store. Having a consistent UoM across all tile sets is a requirement that would be specified in a profile. (Example conceptual mode element “TileUoM=ft”)

Element name: TileSetUOM

==== Requirement 5 - Tile Set Extent

include::requirements/REQ5_core-tileset-extent.adoc[]

In any tiling scheme, there are two extents to be considered. The extent of an individual tile and the extent of the tile set. This requirement is for defining the extent of the tile set.

Note, if there is one tile in a tile set, the extents are identical. In this tiling conceptual model there is no requirement, such as in DGGS, for a tile or tile set to cover the entire globe. A tile or tile set could have an extent that covers a building site, a city, a county, a country, and so forth. Any restrictions on the extent of a tile or tile set would be specified in one or more requirements in a profile or a profile extension.

==== Requirement 6 - Tile Set Origin

include::requirements/REQ6_core-tileset-origin.adoc[]

The tile set origin defines where the spatial origin reference point is for the entire tile set. Typically, for a GIS implemented in the northern hemisphere, the tile set origin would be specified in the coordinates of CRS using the lower left hand corner. This Abstract Specification does not specify where the origin of a tile set is located. There is also not the requirement that all tile set origins in a tiled data store be the same (although having this rule sure helps downstream!). These rules would be specified in a profile or be specific to an implementation. For example, in WMTS the tile set origin is the upper left corner. In any case, there is a tile set origin. 

Example model element: TileSetOrigin=LowerLeftCorner . Other values could be upper left, lower right, upper right and so forth)

==== Requirement 7 - Tile Set Tessellation Type

include::requirements/REQ7_core-tessellation-type.adoc[]

A regular tessellation 2D planar surface can be performed using one of three geometric shapes: squares (rectangles), hexagons, and equilaterial triangles. Squares (rectangles) represent the majority of current and past approaches for tesselating a plane in geospatial systems. However, hexagons have been used in a variety of systems and are the normal tessellation method used in a Discrete Global Grid System (DGGS). Typically there are also rules applied to specify the size and or extent for each tesselation type. For example, in a DGGS implementation, equal area hexagons are often used. In WMTS and TMS, each tile in a tile set as the same width and height.

=== Requirement 8 - tessellation class

Related to the Tile Set Schema is the actual tessellation process used to generate the tile set.

include::requirements/REQ8_core-tessellation.adoc[]

Element name: TileTessellation

=== Requirements Class Tile Schema

The following set of requirements defines the properties of each individual tile. Combined with the Tile Set Schema common properties, there is enough information for any application -server or client - to access, process, analyze, and visualize any geospatial content provided in the tiled structure.

The Tile Schema requirements class is defined as:

include::requirements/rc-tile-schema.adoc[]

==== Requirement 9 - Property Tile Address (ID)

include::requirements/REQ9_tile-address.adoc[]

A tile set shall use a spatial referencing method to assign a unique spatial reference (or index) to each tile across the entire tile set.   These indices may be any alphanumeric string including controlled vocabularies such as the USGS quad index, IP address, tile row/column, or other indexing schemes. The default is sequential numbering beginning at the tile located at the TileSet origin.

Element name: TileAddress

==== Requirement 10 - Property Tile Origin

include::requirements/REQ10_core-tile-origin.adoc[]

The tile origin defines where the spatial origin reference point would be for each individual tile in a tile set. Typically, in a GIS being used in the northern hemisphere, this typically would be the lower left hand corner. All tile origin locations (such as lower left) would be the same for all tiles in a tile set. Neither the conceptual model nor the logical model specifies where the origin of a tile is located. These rules would be specified in a profile or be specific to an implementation. In any case, there is always a tile set origin.

==== Requirement 11 - Property Tile Reference footnoteref[note4, This requirement is based on requirements in the OGC DGGS Abstract Specification.

include::requirements/REQ11_core-tile-reference.adoc[]

Each tile must be referenced at its centroid. This is because the centroid is the only location that will provide a systematic and consistent spatial reference point for all tiles in a tile set regardless of their shape. NOTE: The reference information does not need to be physically stored in the tile set store. The reference can be calculated from the tile extents (see requirement 12).

Element name: TileReference

==== Requirement 12 - Property Tile Extent


